name: Setup dependencies
description: Setup tools and dependencies

inputs:
  install_task:
    description: install task if true
    default: "true"
  task_version:
    description: version of task to install
    default: v3.44.1

runs:
  using: composite
  steps:
    - name: Install task
      if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@v4.0.1
      with:
        uri: https://github.com/go-task/task/releases/download/${{ inputs.task_version }}/task_linux_amd64.tar.gz
        name: task
        version: ${{ inputs.task_version }}