name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Filter
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  test:
    runs-on: ubuntu-24.04
    needs: filter
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Setup node
        if: ${{ startsWith(matrix.service, 'services/node/') || startsWith(matrix.service, 'services/react/') }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: ${{ matrix.service }}/package.json
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
      - name: Setup go
        if: ${{ startsWith(matrix.service, 'services/go/') }}
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum
      - name: Setup poetry
        if: ${{ startsWith(matrix.service, 'services/python/') }}
        uses: snok/install-poetry@v1.4.1
      - name: Setup python
        if: ${{ startsWith(matrix.service, 'services/python/') }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: ${{ matrix.service }}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{ matrix.service }}/poetry.lock
      - name: Install task
        uses: supplypike/setup-bin@v4.0.1
        with:
          uri: https://github.com/go-task/task/releases/download/v3.54.0/task_linux_amd64.tar.gz
          name: task
          version: v3.54.0
      - name: Install app dependencies
        working-directory: ${{ matrix.service }}
        run: task install-ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: task test